"""initial migration

Revision ID: 068fc5f79d54
Revises: 
Create Date: 2021-10-02 06:13:13.428936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '068fc5f79d54'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('locations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=24), nullable=True),
    sa.Column('email', sa.VARCHAR(length=64), nullable=True),
    sa.Column('phone_number', sa.INTEGER(), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=124), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )

    op.create_table('locations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=24), nullable=True),
    sa.Column('event', sa.VARCHAR(length=64), nullable=True),
    sa.Column('timestamp', sa.VARCHAR(), nullable=True),
    sa.Column('date_time', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###
